import type { CanvasData } from '@/types/canvas'

export interface StudioStarterTemplate {
  id: string
  name: string
  description: string
  category: string
  build: () => CanvasData
}

function basePortrait(bg: string): CanvasData['canvas'] {
  return {
    width: 1080,
    height: 1350,
    backgroundColor: bg,
    aspectRatioName: 'portrait',
  }
}

export const STUDIO_STARTER_TEMPLATES: StudioStarterTemplate[] = [
  {
    id: 'promo',
    name: 'Promo launch',
    description: 'Bold headline for product or event launches',
    category: 'Events',
    build: () => ({
      version: '1.0',
      canvas: basePortrait('#0f172a'),
      layers: [
        {
          id: 'accent-bar',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1080,
          height: 12,
          fill: '#3b82f6',
          zIndex: 1,
        },
        {
          id: 'headline',
          type: 'text',
          content: 'Something big is coming',
          x: 80,
          y: 480,
          width: 920,
          fontSize: 68,
          fontFamily: 'Inter',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          zIndex: 2,
        },
        {
          id: 'subtext',
          type: 'text',
          content: 'Stay tuned · Launching soon',
          x: 120,
          y: 620,
          width: 840,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#94a3b8',
          align: 'center',
          zIndex: 2,
        },
      ],
    }),
  },
  {
    id: 'quote',
    name: 'Quote card',
    description: 'Share a testimonial or brand quote',
    category: 'Other',
    build: () => ({
      version: '1.0',
      canvas: basePortrait('#1e293b'),
      layers: [
        {
          id: 'quote-mark',
          type: 'text',
          content: '"',
          x: 80,
          y: 320,
          fontSize: 180,
          fontFamily: 'Georgia',
          fill: '#3b82f6',
          zIndex: 1,
        },
        {
          id: 'headline',
          type: 'text',
          content: 'Your customers said it best.',
          x: 100,
          y: 520,
          width: 880,
          fontSize: 52,
          fontFamily: 'Georgia',
          fontStyle: 'italic',
          fill: '#f8fafc',
          align: 'center',
          zIndex: 2,
        },
        {
          id: 'subtext',
          type: 'text',
          content: '— Your brand',
          x: 120,
          y: 780,
          width: 840,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#64748b',
          align: 'center',
          zIndex: 2,
        },
      ],
    }),
  },
  {
    id: 'sale',
    name: 'Sale announcement',
    description: 'High-impact offer post for retail',
    category: 'Retail',
    build: () => ({
      version: '1.0',
      canvas: basePortrait('#7f1d1d'),
      layers: [
        {
          id: 'badge',
          type: 'circle',
          x: 340,
          y: 280,
          width: 400,
          height: 400,
          fill: '#ef4444',
          zIndex: 1,
        },
        {
          id: 'headline',
          type: 'text',
          content: '30% OFF',
          x: 80,
          y: 420,
          width: 920,
          fontSize: 96,
          fontFamily: 'Impact',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          zIndex: 2,
        },
        {
          id: 'subtext',
          type: 'text',
          content: 'This weekend only · Shop now',
          x: 120,
          y: 560,
          width: 840,
          fontSize: 36,
          fontFamily: 'Inter',
          fill: '#fecaca',
          align: 'center',
          zIndex: 2,
        },
      ],
    }),
  },
  {
    id: 'event',
    name: 'Event invite',
    description: 'Date, time, and CTA for events',
    category: 'Events',
    build: () => ({
      version: '1.0',
      canvas: basePortrait('#312e81'),
      layers: [
        {
          id: 'overlay',
          type: 'rect',
          x: 0,
          y: 900,
          width: 1080,
          height: 450,
          fill: 'rgba(0,0,0,0.45)',
          gradientColors: ['rgba(0,0,0,0)', 'rgba(0,0,0,0.55)'],
          zIndex: 1,
        },
        {
          id: 'headline',
          type: 'text',
          content: 'You\'re invited',
          x: 80,
          y: 960,
          width: 920,
          fontSize: 72,
          fontFamily: 'Inter',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'left',
          zIndex: 2,
        },
        {
          id: 'subtext',
          type: 'text',
          content: 'Saturday · 7 PM · RSVP in bio',
          x: 80,
          y: 1080,
          width: 920,
          fontSize: 32,
          fontFamily: 'Inter',
          fill: '#c7d2fe',
          align: 'left',
          zIndex: 2,
        },
      ],
    }),
  },
  {
    id: 'minimal',
    name: 'Minimal tip',
    description: 'Clean educational or tip post',
    category: 'Tech',
    build: () => ({
      version: '1.0',
      canvas: basePortrait('#fafafa'),
      layers: [
        {
          id: 'headline',
          type: 'text',
          content: '3 tips to grow on Instagram',
          x: 80,
          y: 420,
          width: 920,
          fontSize: 56,
          fontFamily: 'Inter',
          fontStyle: 'bold',
          fill: '#0f172a',
          align: 'left',
          zIndex: 1,
        },
        {
          id: 'line',
          type: 'rect',
          x: 80,
          y: 560,
          width: 120,
          height: 4,
          fill: '#3b82f6',
          cornerRadius: 2,
          zIndex: 1,
        },
        {
          id: 'subtext',
          type: 'text',
          content: 'Swipe for the full breakdown →',
          x: 80,
          y: 600,
          width: 920,
          fontSize: 28,
          fontFamily: 'Inter',
          fill: '#64748b',
          align: 'left',
          zIndex: 1,
        },
      ],
    }),
  },
]
